[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lyapunov_certified_imitation_learning"
version = "0.1.0"
description = "Learn a lyapunov certificate for a neural network"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "numpy",
    "matplotlib",
    "scipy",
    "pandas",
    "plotly",
    "tqdm",
    "casadi",
    "h5py",
    "mpc-datagen @ git+https://github.com/ArgoJ/mpc-datagen.git",
    "auto_LiRPA @ git+https://github.com/Verified-Intelligence/auto_LiRPA.git",
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
