[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lyapunov-certified-imitation-learning"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "numpy",
    "matplotlib",
    "scipy",
    "plotly",
    "tqdm",
    "casadi",
    "h5py",
    "mpc-datagen @ git+https://github.com/ArgoJ/mpc-datagen.git",
    "auto_LiRPA @ git+https://github.com/Verified-Intelligence/auto_LiRPA.git",
    "abcrown @ git+https://github.com/Verified-Intelligence/alpha-beta-CROWN.git",
]

description = "Learn a lyapunov certificate for a neural network"
readme = "README.md"
license = { file = "LICENSE" }
maintainers = [
    { name = "Josua Lindemann", email = "josua.lindemann@outlook.de" },
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "myst-parser"
]
dev = [
    "lyapunov-certified-imitation-learning[test]",
    "lyapunov-certified-imitation-learning[docs]",
    "pre-commit",
    "ruff"
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Repository = "https://github.com/ArgoJ/lyapunov-certified-imitation-learning"
"Bug Tracker" = "https://github.com/ArgoJ/lyapunov-certified-imitation-learning/issues"

[tool.pytest.ini_options]
testpaths = "tests"

[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint.pydocstyle]
convention = "numpy"
